package i5.las2peer.services.mensa;


import java.net.HttpURLConnection;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;

import i5.las2peer.api.Context;
import i5.las2peer.api.ManualDeployment;
import i5.las2peer.api.ServiceException;
import i5.las2peer.api.logging.MonitoringEvent;
import i5.las2peer.restMapper.RESTService;
import i5.las2peer.restMapper.annotations.ServicePath;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Contact;
import io.swagger.annotations.Info;
import io.swagger.annotations.License;
import io.swagger.annotations.SwaggerDefinition;
import org.json.simple.*;

import javax.annotation.security.RolesAllowed;
import org.glassfish.jersey.server.filter.RolesAllowedDynamicFeature;


import java.util.HashMap;
import java.util.Map;
 

/**
 *
 * 404
 *
 * This microservice was generated by the CAE (Community Application Editor). If you edit it, please
 * make sure to keep the general structure of the file and only add the body of the methods provided
 * in this main file. Private methods are also allowed, but any "deeper" functionality should be
 * outsourced to (imported) classes.
 *
 */
@ServicePath("mensa")
@ManualDeployment
public class Mensa extends RESTService {





  public Mensa() {
	super();
    // read and set properties values
    setFieldValues();
    
  }

  @Override
  public void initResources() {
	getResourceConfig().register(RootResource.class);
	getResourceConfig().register(RolesAllowedDynamicFeature.class);
  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // REST methods
  // //////////////////////////////////////////////////////////////////////////////////////

  @Api
  @SwaggerDefinition(
      info = @Info(title = "404", version = "0.0.0",
          description = "",
          termsOfService = "",
          contact = @Contact(name = "", email = "CAEAddress@gmail.com") ,
          license = @License(name = "BSD",
              url = "https://github.com/PhilCAEOrg2/microservice-404/blob/master/LICENSE.txt") ) )
  @Path("/")
  public static class RootResource {

    private final Mensa service = (Mensa) Context.getCurrent().getService();

      /**
   * 
   * getDishById
   *
   * 
   * @param name  a String
   * @param id  a String

   * 
   * @return Response 
   * 
   */
  @GET
  @Path("/dishes/{id}/{name}")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "res")
  })
  @ApiOperation(value = "getDishById", notes = " ")
  public Response getDishById(@PathParam("name") String name, @PathParam("id") String id) {




     
    // service method invocations

     




    // res
    boolean res_condition = true;
    if(res_condition) {
      JSONObject res = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_OK).entity(res.toJSONString()).build();
    }
    return null;
  }

  /**
   * 
   * abc
   *
   * 
   * @param id Id of the dish to which a rating should be added. a String
   * @param body Dish rating that should be added. a JSONObject

   * 
   * @return Response Dish rating created successfully.
   * 
   */
  @POST
  @Path("/abc/{id}")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.APPLICATION_JSON)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_BAD_REQUEST, message = "Given dish rating has no valid format."),
       @ApiResponse(code = HttpURLConnection.HTTP_CREATED, message = "Dish rating created successfully.")
  })
  @ApiOperation(value = "abc", notes = " ")
  public Response abc(@PathParam("id") String id, String body) {
   classes.DishRating payloadbodyObject = new classes().new DishRating();
   try { 
       payloadbodyObject.fromJSON(body);
   } catch (Exception e) { 
       e.printStackTrace();
       JSONObject result = new JSONObject();
       return Response.status(HttpURLConnection.HTTP_INTERNAL_ERROR).entity("Cannot convert json to object").build();
   }



     
    // service method invocations

     




    // badRequest
    boolean badRequest_condition = true;
    if(badRequest_condition) {
      JSONObject badRequest = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_BAD_REQUEST).entity(badRequest.toJSONString()).build();
    }
    // created
    boolean created_condition = true;
    if(created_condition) {
      JSONObject created = new classes().new DishRating().toJSON();

      

      return Response.status(HttpURLConnection.HTTP_CREATED).entity(created.toJSONString()).build();
    }
    return null;
  }

  /**
   * 
   * listDishes
   *
   * 
   *
   * 
   * @return Response Returns list of available dishes.
   * 
   */
  @GET
  @Path("/dishes")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "Returns list of available dishes.")
  })
  @ApiOperation(value = "listDishes", notes = " ")
  public Response listDishes() {




     
    // service method invocations

     




    // ok
    boolean ok_condition = true;
    if(ok_condition) {
      JSONObject ok = new JSONObject();

      

      return Response.status(HttpURLConnection.HTTP_OK).entity(ok.toJSONString()).build();
    }
    return null;
  }



  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // Service methods (for inter service calls)
  // //////////////////////////////////////////////////////////////////////////////////////
  
  

  // //////////////////////////////////////////////////////////////////////////////////////
  // Custom monitoring message descriptions (can be called via RMI)
  // //////////////////////////////////////////////////////////////////////////////////////

  public Map<String, String> getCustomMessageDescriptions() {
    Map<String, String> descriptions = new HashMap<>();
    
    return descriptions;
  }

}
